### ISSUE TITLE
build macOS failed

### ISSUE THREAD

**Issue by ryanaltair** [netease-kit/NIM-Flutter-SDK#6]
```bash
cd /Users/ryanaltair/github/xx/NIM-Flutter-SDK/nim_core_macos/example/macos
[        ]     builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg
-resolve-src-symlinks -rename
/Users/ryanaltair/github/xx/NIM-Flutter-SDK/nim_core_macos/example/build/macos/Build/Intermediates.noindex/R
unner.build/Debug/Runner.build/Objects-normal/x86_64/example.swiftsourceinfo
/Users/ryanaltair/github/xx/NIM-Flutter-SDK/nim_core_macos/example/build/macos/Build/Products/Debug/example.
swiftmodule/Project/x86_64-apple-macos.swiftsourceinfo
[   +6 ms] ** BUILD FAILED **
[        ] The following build commands failed:
[        ] 	Ld
/Users/ryanaltair/github/xx/NIM-Flutter-SDK/nim_core_macos/example/build/macos/Build/Products/Debug/example.
app/Contents/MacOS/example normal (in target 'Runner' from project 'Runner')
[        ] (1 failure)
[  +26 ms] Building macOS application... (completed in 5.5s)
[+1320 ms] Exception: Build process failed
[  +10 ms] "flutter run" took 8,335ms.
[  +15 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +259 ms] ensureAnalyticsSent: 254ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
```
NIM_core version: `1.0.0-rc.19  1.0.0-rc.20 1.0.0-rc.48`
macOS version : `12.3.1`
flutter version
```
Flutter 2.10.5 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision 5464c5bac7 (13 days ago) • 2022-04-18
09:55:37 -0700
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2
```

more info:
MacBook Pro (14-inch, 2021)
Chip Apple M1 Max

**Comment by ryanaltair** [comment]
here is log with` flutter build -d macos --v`
[error_vv.log](https://github.com/netease-kit/NIM-Flutter-SDK/files/8649490/error_vv.log)

**Comment by stephenzhj** [comment]
see https://github.com/RevenueCat/purchases-flutter/issues/125

**Comment by stephenzhj** [comment]
> here is log with` flutter build -d macos --v` [error_vv.log](https://github.com/netease-kit/NIM-Flutter-SDK/files/8649490/error_vv.log)

see https://github.com/RevenueCat/purchases-flutter/issues/125

**Comment by ryanaltair** [comment]
```bash
[   +1 ms]   "nim_cpp_wrapper_util::Json::Value::operator[](std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
[        ]       Convert::convertJson2Map(std::__1::map<flutter::EncodableValue, flutter::EncodableValue, std::__1::less<flutter::EncodableValue>, std::__1::allocator<std::__1::pair<flutter::EncodableValue const, flutter::EncodableValue> > >&, nim_cpp_wrapper_util::Json::Value const&) const in nim_core_macos(FLTConvert.o)
[   +3 ms]   "nim_cpp_wrapper_util::Json::Value::operator[](int) const", referenced from:
[        ]       Convert::convertJson2List(std::__1::vector<flutter::EncodableValue, std::__1::allocator<flutter::EncodableValue> >&, nim_cpp_wrapper_util::Json::Value const&) const in nim_core_macos(FLTConvert.o)
[   +3 ms] ld: symbol(s) not found for architecture x86_64
[   +6 ms] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[   +1 ms] Copy /Users/ryanaltair/github/ryanaltair/counter/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources/counter-Swift.h /Users/ryanaltair/github/ryanaltair/counter/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/counter-Swift.h (in target 'Runner' from project 'Runner')
[        ]     cd /Users/ryanaltair/github/ryanaltair/counter/macos
[        ]     builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/ryanaltair/github/ryanaltair/counter/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/counter-Swift.h /Users/ryanaltair/github/ryanaltair/counter/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources
[        ] Copy /Users/ryanaltair/github/ryanaltair/counter/build/macos/Build/Products/Debug/counter.swiftmodule/x86_64-apple-macos.swiftmodule /Users/ryanaltair/github/ryanaltair/counter/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/counter.swiftmodule (in target 'Runner' from project 'Runner')
[        ]     cd /Users/ryanaltair/github/ryanaltair/counter/macos
[        ]     builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks -rename /Users/ryanaltair/github/ryanaltair/counter/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/counter.swiftmodule /Users/ryanaltair/github/ryanaltair/counter/build/macos/Build/Products/Debug/counter.swiftmodule/x86_64-apple-macos.swiftmodule
[        ] Copy /Users/ryanaltair/github/ryanaltair/counter/build/macos/Build/Products/Debug/counter.swiftmodule/x86_64-apple-macos.swiftdoc /Users/ryanaltair/github/ryanaltair/counter/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/counter.swiftdoc (in target 'Runner' from project 'Runner')
[        ]     cd /Users/ryanaltair/github/ryanaltair/counter/macos
[        ]     builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks -rename /Users/ryanaltair/github/ryanaltair/counter/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/counter.swiftdoc /Users/ryanaltair/github/ryanaltair/counter/build/macos/Build/Products/Debug/counter.swiftmodule/x86_64-apple-macos.swiftdoc
[        ] Copy /Users/ryanaltair/github/ryanaltair/counter/build/macos/Build/Products/Debug/counter.swiftmodule/Project/x86_64-apple-macos.swiftsourceinfo /Users/ryanaltair/github/ryanaltair/counter/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/counter.swiftsourceinfo (in target 'Runner' from project 'Runner')
[        ]     cd /Users/ryanaltair/github/ryanaltair/counter/macos
[        ]     builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks -rename /Users/ryanaltair/github/ryanaltair/counter/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/counter.swiftsourceinfo /Users/ryanaltair/github/ryanaltair/counter/build/macos/Build/Products/Debug/counter.swiftmodule/Project/x86_64-apple-macos.swiftsourceinfo
[ +213 ms] ** BUILD FAILED **
[        ] The following build commands failed:
[        ] 	Ld /Users/ryanaltair/github/ryanaltair/counter/build/macos/Build/Products/Debug/counter.app/Contents/MacOS/counter normal (in target 'Runner' from project 'Runner')
[        ] (1 failure)
[  +26 ms] Building macOS application... (completed in 40.4s)
[   +5 ms] Exception: Build process failed
[   +5 ms] "flutter run" took 51,675ms.
[  +16 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +226 ms] ensureAnalyticsSent: 222ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```
[Uploading error_vv.log…]()

**Comment by ryanaltair** [comment]
setting   nim_core_macos.podspec `s.platform = :osx, '12.1'`
[Uploading error_vv.log…]()

**Comment by stephenzhj** [comment]
> setting nim_core_macos.podspec `s.platform = :osx, '12.1'` [error_vv.log.zip](https://github.com/netease-kit/NIM-Flutter-SDK/files/8659417/error_vv.log.zip)

cmake: command not found

**Comment by ryanaltair** [comment]
after install cmake 
```bash
which cmake
/opt/homebrew/bin/cmake
```
[error_cmake.log.zip](https://github.com/netease-kit/NIM-Flutter-SDK/files/8659658/error_cmake.log.zip)
