### ISSUE TITLE
build windows failed

### ISSUE THREAD

**Issue by ryanaltair** [netease-kit/NIM-Flutter-SDK#7]
nim_core version : 1.0.0-rc.48

```
PS C:\xx\counter-main> flutter --version                                      
Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git      Framework • revision 5464c5bac7 (3 weeks ago) • 2022-04-18 09:55:37 -0700     Engine • revision 57d3bac3dd                                                  Tools • Dart 2.16.2 • DevTools 2.9.2    
```
```
PS C:\xx\counter-main> flutter doctor                                         
Doctor summary (to see all details, run flutter doctor -v):                   
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version               10.0.19044.1682], locale zh-CN)                                           [√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)[√] VS Code, 64-bit edition (version 1.66.2)                                 [√] Connected device (1 available) 
```
error is 

```
r-main\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
[        ]   C:\xx\counter-main\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/api/nim_
cpp_rts.h(69,18): warning C4996: 'nim_cpp_wrapper_util::Json::FastWriter::write': Use StreamWriterBuilder instead [C:\xx\counter-mai
n\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
[        ]   C:\xx\counter-main\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_wrapper_util/nim_sdk
_util.h(75,13): warning C4505: "nim::nim_print_unfound_func_name": 宸插垹闄ゅ叿鏈夊唴閮ㄩ摼鎺ョ殑鏈紩鐢ㄥ嚱鏁?[C:\xx\counter-main\build\windows\plugins\
nim_core_windows\nim_core_windows_plugin.vcxproj]
[        ]   C:\xx\counter-main\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_wrapper_util/nim_sdk
_util.h(79,13): warning C4505: "nim::unfound_function_holder": 宸插垹闄ゅ叿鏈夊唴閮ㄩ摼鎺ョ殑鏈紩鐢ㄥ嚱鏁?[C:\xx\counter-main\build\windows\plugins\nim_
core_windows\nim_core_windows_plugin.vcxproj]
[        ] 鈥淐:\xx\counter-main\build\windows\INSTALL.vcxproj鈥?榛樿鐩爣) (1) ->
[        ] 鈥淐:\xx\counter-main\build\windows\ALL_BUILD.vcxproj鈥?榛樿鐩爣) (3) ->
[        ] 鈥淐:\xx\counter-main\build\windows\runner\counter.vcxproj鈥?榛樿鐩爣) (4) ->
[        ] 鈥淐:\xx\counter-main\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj鈥?榛樿鐩爣) (7) ->
[        ] (ClCompile 鐩爣) -> 
[        ]   C:\xx\counter-main\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_chatroom_cpp_wrapper
/helper/nim_chatroom_helper.h(108,37): error C2220: 浠ヤ笅璀﹀憡琚涓洪敊璇?[C:\xx\counter-main\build\windows\plugins\nim_core_windows\nim_cor
e_windows_plugin.vcxproj]
[        ]     642 涓鍛?[        ]     1 涓敊璇?[        ] 宸茬敤鏃堕棿 00:01:05.41
[  +27 ms] Building Windows application... (completed in 69.5s)
[   +1 ms] "flutter windows" took 70,070ms.
[   +3 ms] Build process failed.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runBuild (package:flutter_tools/src/windows/build_windows.dart:314:5)
           <asynchronous suspension>
           #2      buildWindows (package:flutter_tools/src/windows/build_windows.dart:80:5)
           <asynchronous suspension>
           #3      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:57:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart
:281:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +144 ms] ensureAnalyticsSent: 143ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```
log is here 🔽
[log.txt](https://github.com/netease-kit/NIM-Flutter-SDK/files/8644282/log.txt)

**Comment by xiaoge136** [comment]
Duplicate of #1 

Delete /WX from CMakeLists.txt

**Comment by ryanaltair** [comment]
> Duplicate of #1
> 
> Delete /WX from CMakeLists.txt

It does works.
